name: Run build

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Get image name
        id: image_name
        run: |
          image_name=${GITHUB_REPOSITORY,,}
          echo "::set-output name=IMAGE_NAME::${image_name}:latest"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ steps.image_name.outputs.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
